### ISSUE TITLE
Handle socket.gaierror

### ISSUE THREAD

**Issue by laixintao** [laixintao/pingtop#15]
```
~ pingtop aaaa
RROR:root:[Errno 8] nodename nor servname provided, or not known
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.7.1/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/laixintao/Program/pingtop/pingtop.py", line 239, in forever_ping
    dest_ip = socket.gethostbyname(dest)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

- set a smaller timeout
- display `SERVFAIL` at the IP column

![image](https://user-images.githubusercontent.com/9675939/55852877-4c4cd500-5b91-11e9-9c53-415848b848fd.png)

**Comment by laixintao** [comment]
fixed via https://github.com/laixintao/pingtop/pull/28
