### ISSUE TITLE
Pingtop stops pinging servers and issues various error messages

### ISSUE THREAD

**Issue by Duayne2001** [laixintao/pingtop#33]
Tried the script on 2 different KVM VPS running Debian 10 x64. Installed via apt install python3-pip and pip3 install pingtop.

Running the script directly as root gives me these error messages. Any idea what's going wrong here?
![pingtop-1](https://user-images.githubusercontent.com/76791505/107833265-0071a500-6d93-11eb-8209-74faee6c67a5.jpg)
![pingtop-2](https://user-images.githubusercontent.com/76791505/107833270-04052c00-6d93-11eb-8107-a9bb6b64f54f.jpg)
![pingtop-3](https://user-images.githubusercontent.com/76791505/107833275-0798b300-6d93-11eb-9bf5-e6a7946013e0.jpg)

**Comment by godet71** [comment]
Hi, I had was same problem.
How to fix this problem?

Could please help me..

**Comment by laixintao** [comment]
Hi thanks for reporting, I have tried on ubuntu20.04 and can't reproduce it. From @Duayne2001 's screenshot I think there are some ASCII issues. Are you also on Debian? @godet71

**Comment by godet71** [comment]
Hi, I have tried to in Mac OS, Is that same as ASCII issues?

Is this use only Debian Series?

**Comment by laixintao** [comment]
can you try with latest verion https://pypi.org/project/pingtop/0.4.0/
and under Python 3.8.5?

**Comment by Duayne2001** [comment]
> can you try with latest verion https://pypi.org/project/pingtop/0.4.0/
> and under Python 3.8.5?

Do you mean Python = 3.8.5 or < 3.8.5, i.e. for example 3.8.4?

**Comment by laixintao** [comment]
I think 3.8.x are all good.

**Comment by godet71** [comment]
Hi I would installed pingtop 0.4.0, but doesn't installed.
Also, I was run python3.8.4 pingtop 0.3.0, but below on occured error.

Please check.

```
Traceback (most recent call last):
  File "./pingtop", line 11, in <module>
    load_entry_point('pingtop==0.3.0', 'console_scripts', 'pingtop')()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pingtop/__init__.py", line 427, in multi_ping
    tablebox = MainBox(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pingtop/__init__.py", line 210, in __init__
    self.table = PingDataTable(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pingtop/__init__.py", line 193, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'border'
```

**Comment by laixintao** [comment]
0.3.x no longer works, there are dependencies break.

Why can't you install 0.4.0?

**Comment by rbarzic** [comment]
Same issues with the latest version from github. Problems seem to appear when some hosts are not reachable
roba@onio-ltp04  17:29:04  pip freeze                                                                                                                                                                
blist==1.3.6
click==8.0.3
orderedattrdict==1.6.0
panwid==0.2.5
-e git+https://github.com/laixintao/pingtop.git@75353119db1af8635fec85a9bf38722e152c426c#egg=pingtop
raccoon==2.1.5
six==1.16.0
tabulate==0.8.9
urwid==2.1.2
urwid-utils==0.1.2

Maybe it would be a good idea if you could post the version of the modules you are using. As  panwid is the only module specified with a version, I would not be surprised that the issue is in a specific version of one of the other modules

lsb_release -a                                                                                                                                                            
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

roba@onio-ltp04  17:31:12  python --version                                                                                                                                                            
Python 3.8.10

**Comment by laixintao** [comment]
Hi can you try to install from pypi instead of from git?
