### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'border'

### ISSUE THREAD

**Issue by mortymacs** [laixintao/pingtop#35]
Hi,

I got this error on the latest stable version:
```
> pingtop google.com bing.com
Traceback (most recent call last):
  File "/usr/bin/pingtop", line 33, in <module>
    sys.exit(load_entry_point('pingtop==0.3.0', 'console_scripts', 'pingtop')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pingtop/__init__.py", line 427, in multi_ping
    tablebox = MainBox(
  File "/usr/lib/python3.9/site-packages/pingtop/__init__.py", line 210, in __init__
    self.table = PingDataTable(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pingtop/__init__.py", line 193, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'border'
```

Python version: 3.9
OS: ArchLinux

**Comment by laixintao** [comment]
denpendency problems, please try https://pypi.org/project/pingtop/0.4.0/ with Python3.8

**Comment by rbarzic** [comment]
pip install pingtop==0.4.0
ERROR: Could not find a version that satisfies the requirement pingtop==0.4.0 (from versions: 0.4.0.macosx-10.15-x86_64, 0.0.1, 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.11, 0.2.12, 0.2.13, 0.2.14, 0.3.0)
ERROR: No matching distribution found for pingtop==0.4.0

How can I get this version ?

**Comment by rbarzic** [comment]
This works -there is actually no version 0.4.0 tagged :
https://github.com/laixintao/pingtop.git#egg=pingtop

**Comment by laixintao** [comment]
sorry i didn't get you.

there is 4.0 tag on github: https://github.com/laixintao/pingtop/releases/tag/v0.4.0

and there is uploaded version in pypi: https://pypi.org/project/pingtop/0.4.0/
